In [1]:
import torch

1) Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

2) Create a random tensor with shape (7, 7).

In [3]:
tensor = torch.rand(size = (7,7))
tensor,tensor.shape


(tensor([[0.1798, 0.4475, 0.6315, 0.4976, 0.3559, 0.4276, 0.5125],
         [0.0203, 0.9890, 0.3772, 0.7217, 0.9131, 0.5005, 0.2675],
         [0.3430, 0.5922, 0.7580, 0.4986, 0.7712, 0.3339, 0.2362],
         [0.1427, 0.5709, 0.7757, 0.9367, 0.6745, 0.4646, 0.8139],
         [0.8818, 0.0733, 0.2670, 0.5991, 0.2714, 0.1026, 0.8351],
         [0.0598, 0.9365, 0.9659, 0.7761, 0.2031, 0.7135, 0.2111],
         [0.9322, 0.0765, 0.3383, 0.9018, 0.3401, 0.5078, 0.7553]]),
 torch.Size([7, 7]))

3) Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [5]:
# creating a tensor of shape(1,7)
tensor_a = torch.rand(size = (1,7))
tensor_a

tensor([[0.0556, 0.0676, 0.7940, 0.3507, 0.4939, 0.1195, 0.6678]])

Matrix multiplication with out previous tensor (7,7) and the new tensor (1,7) is not possible as the inner dimensions are not the same. So we need to take matrix transpose of tensor_a for performing the matrix multiplication

In [10]:
tensor_a = tensor_a.T
tensor_mm = torch.mm(tensor,tensor_a)
tensor_mm

tensor([[1.2853],
        [1.3101],
        [1.4145],
        [1.9233],
        [1.1802],
        [1.4324],
        [1.3750]])

4) Set the random seed to 0 and do exercises 2 & 3 over again.

In [5]:
RANDOM_SEED = 0
torch.manual_seed(seed= RANDOM_SEED)
tensor_A = torch.rand(size=(7,7))
torch.manual_seed(seed= RANDOM_SEED)
tensor_B = torch.rand(size=(1,7))
#Performing matrixmultiplication
tensor_mm = torch.mm(tensor_A,tensor_B.T)
tensor_mm

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

5) Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234

In [7]:
# for gpu
torch.cuda.manual_seed(1234)

6) Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [8]:
# creating random tensors
RANDOM_SEED = 1234
torch.manual_seed(seed=RANDOM_SEED)
tensor_X = torch.rand(size=(2,3))
torch.manual_seed(seed=RANDOM_SEED)
tensor_Y = torch.rand(size=(2,3))


In [11]:
# sending them to GPU
tensor_X = tensor_X.to(device="cuda")
tensor_Y = tensor_Y.to(device='cuda')

7) Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors)

In [14]:
tensor_mm = torch.mm(tensor_X,tensor_Y.T)
tensor_mm

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

8) Find the maximum and minimum values of the output of 7.

In [15]:
min_value = torch.min(tensor_mm)
max_value = torch.max(tensor_mm)
print(f"Minimum: {min_value}")
print(f"Maximum: {max_value}")


Minimum: 0.21611443161964417
Maximum: 0.628727912902832


9) Find the maximum and minimum index values of the output of 7.

In [17]:
max_index = torch.argmax(tensor_mm)
min_index = torch.argmin(tensor_mm)
max_index,min_index

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))

10) Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [24]:
torch.manual_seed(seed=7)
inital_tensor = torch.rand(size=(1,1,1,10))
inital_tensor,inital_tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [23]:
new_tensor = inital_tensor.reshape(10)
new_tensor,new_tensor.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))