In [1]:
import torch

1) Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

2) Create a random tensor with shape (7, 7).

In [3]:
tensor = torch.rand(size = (7,7))
tensor,tensor.shape


(tensor([[0.1798, 0.4475, 0.6315, 0.4976, 0.3559, 0.4276, 0.5125],
         [0.0203, 0.9890, 0.3772, 0.7217, 0.9131, 0.5005, 0.2675],
         [0.3430, 0.5922, 0.7580, 0.4986, 0.7712, 0.3339, 0.2362],
         [0.1427, 0.5709, 0.7757, 0.9367, 0.6745, 0.4646, 0.8139],
         [0.8818, 0.0733, 0.2670, 0.5991, 0.2714, 0.1026, 0.8351],
         [0.0598, 0.9365, 0.9659, 0.7761, 0.2031, 0.7135, 0.2111],
         [0.9322, 0.0765, 0.3383, 0.9018, 0.3401, 0.5078, 0.7553]]),
 torch.Size([7, 7]))

3) Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [5]:
# creating a tensor of shape(1,7)
tensor_a = torch.rand(size = (1,7))
tensor_a

tensor([[0.0556, 0.0676, 0.7940, 0.3507, 0.4939, 0.1195, 0.6678]])

Matrix multiplication with out previous tensor (7,7) and the new tensor (1,7) is not possible as the inner dimensions are not the same. So we need to take matrix transpose of tensor_a for performing the matrix multiplication

In [10]:
tensor_a = tensor_a.T
tensor_mm = torch.mm(tensor,tensor_a)
tensor_mm

tensor([[1.2853],
        [1.3101],
        [1.4145],
        [1.9233],
        [1.1802],
        [1.4324],
        [1.3750]])