In [1]:
#import pytorch
import torch


In [2]:
#checking the version of pytorch
torch.__version__

'2.4.1+cu124'

## Tensors
Tensors are builiding blocks or container which can house data in N dimensions.
Tensors can be created using class torch.Tensor
Note:
1) scalars are zero rank(or dimension) tensor
2) vectors are one rank(or dimesnion) tensor
3) Matrices are 2 rank(or dimension) tensor

In [9]:
#creating scalar
scalar = torch.tensor(2)
print(scalar.item())
print(scalar.ndim)# dimension of tensor
print(scalar.shape)


2
0
torch.Size([])


In [5]:
#creating vectors
vector = torch.tensor([2,3])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([2, 3])
1
torch.Size([2])


In [14]:
#creating matrix
matrix = torch.tensor([[2,3],[3,4]])
matrix.ndim # 2
matrix.shape

torch.Size([2, 2])

In [17]:
#creating a tensor
TENSOR = torch.tensor([[[2,3,1]
                        ,[3,4,3]]])
TENSOR.ndim # 3
TENSOR.shape # (1,2,3)

torch.Size([1, 2, 3])

In [23]:
# Lets practise some more
# TENSOR_1 = torch.tensor([[[2,3,4,5],
#                           [3,4,5],
#                           [3,4,5]]])
# TENSOR_1.ndim # This will throw error as the elements are of different dimesnions

TENSOR_2 = torch.tensor([[[2,3],
                          [3,4],
                          [9,8],
                          [3,8]]])
TENSOR_2.ndim # 3
TENSOR_2.shape #(1,4,2)

TENSOR_3 = torch.tensor([[[[2,3],
                           [3,4],
                           [5,6]],
                           [[2,3],
                            [4,5],
                            [1,1]]]])
TENSOR_3.ndim #4
TENSOR_3.shape ## [1,2,3,2]

torch.Size([1, 2, 3, 2])

### Random Tensors
Creating Random tensor with the method torch.rand() with size parameters.
Lets create random tensors with above dimensions


In [28]:
# creating random tensor of size(2,2)
random_tensor = torch.rand(size=(2,2))
print(random_tensor)
#creating tensor of size (1,2,3,2)
random_tensor1 = torch.rand(size=(1,2,3,2))
print(random_tensor1)

#creating an tensor for common image shape (224,224,3)
image_tensor = torch.rand(size = (224,224,3)) #(heigtht,width,colorchannels)
image_tensor


tensor([[0.0996, 0.1792],
        [0.3859, 0.3250]])
tensor([[[[0.8024, 0.8551],
          [0.6709, 0.0129],
          [0.9996, 0.5144]],

         [[0.8459, 0.1175],
          [0.9421, 0.2515],
          [0.4986, 0.4943]]]])


tensor([[[0.0150, 0.6904, 0.0415],
         [0.1192, 0.7050, 0.9442],
         [0.8003, 0.4289, 0.5674],
         ...,
         [0.9030, 0.8946, 0.2433],
         [0.1128, 0.9165, 0.0277],
         [0.5469, 0.6940, 0.6750]],

        [[0.6423, 0.2284, 0.9378],
         [0.5158, 0.2379, 0.2677],
         [0.2932, 0.5081, 0.1231],
         ...,
         [0.6051, 0.9254, 0.1196],
         [0.4678, 0.6555, 0.4571],
         [0.8275, 0.5739, 0.2814]],

        [[0.9252, 0.4298, 0.8242],
         [0.7110, 0.6437, 0.2238],
         [0.7320, 0.6759, 0.5130],
         ...,
         [0.2449, 0.9922, 0.9406],
         [0.9743, 0.0033, 0.9036],
         [0.8470, 0.9124, 0.9759]],

        ...,

        [[0.0754, 0.1630, 0.6968],
         [0.7538, 0.3959, 0.2796],
         [0.1434, 0.7641, 0.0442],
         ...,
         [0.2873, 0.4422, 0.2898],
         [0.1383, 0.1386, 0.9115],
         [0.8316, 0.6834, 0.7032]],

        [[0.7664, 0.2565, 0.9344],
         [0.6821, 0.3336, 0.7141],
         [0.

Now, lets create tensors of ones and zeros using torch.zeros and torch.ones

In [30]:
#creating zeros tensor
zeros = torch.zeros(size=(1,2,3))
zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [33]:
#creating ones tensor
ones = torch.ones(size = (3,4,1))
ones

tensor([[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]])

We can also create a range of tensor using torch.arange(start,end,steps)

In [41]:
zero_to_ten = torch.arange(0,10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
tens_to_hun = torch.arange(start=10,end=100,step=1)
tens_to_hun
# Note you cant create a range in descending order

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

sometimes if you want a zero or one tensor with the shape of a already existing tensor that you can achieve it through torch.zeros_like(input = tensor_name) and torch.ones_like(input = tensor_name)

In [6]:
# creating a zeros_like tensor for the tensor above(tens_to_hun)
zeros_tens_to_hun = torch.zeros_like(input = tens_to_hun)
zeros_tens_to_hun

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# now same for the ones_like
ones_like_tens_to_hun = torch.ones_like(tens_to_hun)
ones_like_tens_to_hun

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatype
Default datatype in tensors is float32. Pytorch wants every tensor to be in a same format and device

In [9]:
default_tensor = torch.tensor([3.9,3.7,3.4],
                              dtype=None,# default i.e float32
                              device = None,#default to cpu
                              requires_grad=False
                              )
default_tensor.shape,default_tensor.dtype,default_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [10]:
# creating a tensor with float 16 datatype
float_16_tensor = torch.tensor([2,3,4],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

The most common errors in Pytorch arises due to :
1) shape of tensor
2) datatype of tensor
3) device where tensor is stored

## Manupilating tensors
Some of the tensor operation are as follows
1) Addition
2) Subtractions
3) Multiplication(element wise)
4) Division
5) Matrix Multiplication (MOST IMPORTANT)

In [11]:
# lets create a tensor of values
tensor = torch.tensor([2,3,4])
tensor += 5
tensor,tensor.dtype

(tensor([7, 8, 9]), torch.int64)

In [9]:
# lets multiply all the elements with 10
tensor *= 10
tensor,tensor.dtype

(tensor([70., 80., 90.]), torch.float32)

In [10]:
# lets divide it by 10
tensor = tensor/10
tensor,tensor.dtype

(tensor([7., 8., 9.]), torch.float32)

In [16]:
# multiplying using torch.multiply
tensor = torch.multiply(tensor,10)
tensor,tensor.dtype


(tensor([70000, 80000, 90000]), torch.int64)

### Matrix Multiplication
In pytorch we use the method torch.matmul() 

In [17]:
Tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [33]:
torch.matmul(Tensor,Tensor)


tensor(14)

In [22]:
# matrix multiplication of two tensors A and B
tensor_A = torch.tensor([[2,3,4,5],
                         [2,1,6,7]])# size of(2,4)
tensor_B = torch.tensor([[2,3,4,5],
                         [3,2,1,5]])# size of (2,4)

Since the inner dimensions dont match. We can only opearte matrix multiplication after obtaining transpose of tensor_B making their inner dimension match(4=4)

In [23]:
print(tensor_A)
print(tensor_B)

tensor([[2, 3, 4, 5],
        [2, 1, 6, 7]])
tensor([[2, 3, 4, 5],
        [3, 2, 1, 5]])


In [27]:
tensor_B = tensor_B.T # transpose operation
tensor_B

tensor([[2, 3],
        [3, 2],
        [4, 1],
        [5, 5]])

In [28]:
# tensors after tranpose
print(tensor_A)
print(tensor_B)

tensor([[2, 3, 4, 5],
        [2, 1, 6, 7]])
tensor([[2, 3],
        [3, 2],
        [4, 1],
        [5, 5]])


In [29]:
# Matrix multiplication
mat_mut = torch.matmul(tensor_A,tensor_B)
mat_mut # size is (2,2)

tensor([[54, 41],
        [66, 49]])

In [30]:
# checking for the datatype
mat_mut.dtype

torch.int64

when doing torch.matmul it preserves the initial data type and doesnt convert into the default datatype

In [31]:
# using torch.mm() method
mm = torch.mm(tensor_A,tensor_B)
mm,mm.shape,mm.dtype

(tensor([[54, 41],
         [66, 49]]),
 torch.Size([2, 2]),
 torch.int64)

#### Finding the min,max,mean,sum etc

In [2]:
# creating a tensor 
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
print(f"Min: {x.min()}")
print(f"Max: {x.max()}")
# print(f"Mean: {x.mean()}") # this will throw error because it requires tensors to be a float32 dtype
print(f"Sum: {x.sum()}")

Min: 0
Max: 90
Sum: 450


In [8]:
x = x.type(torch.float32) # changing datatype from int64 to float32
print(f"Mean: {x.mean()}")

Mean: 45.0


The lower the datatype the faster the computation. Eg: float32 is faster computation than float64 or int64 but less accurate

### Reshaping,stacking,squezzing and unsqueezing
These are techniques that aid in manupulating tensors with shape mismatches

In [26]:
# lets create a tensor 
y = torch.arange(0,100,10)
y.shape,y.dtype,y.ndim

(torch.Size([10]), torch.int64, 1)

### Reshape
torch.reshape() returns a tensor wiht the same data and number of elements as input, but with the specified shape

In [25]:
y_reshaped= y.reshape(1,10) # 1 is the specified shape
y_reshaped.ndim# 2 because we have added 1 extra dimesion


2

In [22]:
torch.reshape(y,(1,10))


tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [32]:
# we can also change the view with torch.view()
z = y.view(1,10)
z,z.shape

(tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), torch.Size([1, 10]))

Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.

So changing the view changes the original tensor too.

In [35]:
z[:,0] = 10
z,y

(tensor([[10, 10, 20, 30, 40, 50, 60, 70, 80, 90]]),
 tensor([10, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

### Stacking
stacks one tensor over the other accoriding to the parameters provided

In [48]:
# use of torch.stack()
y_stacked = torch.stack([y,y,y,y],dim=0) # Observe
y_stacked1 = torch.stack([y,y,y,y],dim=1)# Observe
y_stacked,y_stacked1

(tensor([[10, 10, 20, 30, 40, 50, 60, 70, 80, 90],
         [10, 10, 20, 30, 40, 50, 60, 70, 80, 90],
         [10, 10, 20, 30, 40, 50, 60, 70, 80, 90],
         [10, 10, 20, 30, 40, 50, 60, 70, 80, 90]]),
 tensor([[10, 10, 10, 10],
         [10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30],
         [40, 40, 40, 40],
         [50, 50, 50, 50],
         [60, 60, 60, 60],
         [70, 70, 70, 70],
         [80, 80, 80, 80],
         [90, 90, 90, 90]]))

### Squeeze
It essentially removes all single dimensions from a tensor. YOu can only apply this to dimensions higher than 1

In [54]:
# we take a tensor of 2 dimensions
y_reshaped,y_reshaped.shape

(tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), torch.Size([1, 10]))

In [55]:
# lets squeeze the tensor y_reshaped
print(f"Previous tensor: {y_reshaped} ")
print(f"Previous tensor size: {y_reshaped.shape} ")
# after squeezing
squeezed_y = y_reshaped.squeeze()
print(f"Present tensor: {squeezed_y} ")
print(f"Present tensor size: {squeezed_y.shape} ")# 1D is removed

Previous tensor: tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]) 
Previous tensor size: torch.Size([1, 10]) 
Present tensor: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]) 
Present tensor size: torch.Size([10]) 


### Unsqueeze 
The reverse action of squeeze is unsqueeze. It adds a dimension value of 1 at a specific index

In [59]:
print(f"Previous squeezed tensor: {squeezed_y}")
print(f"Previous squeezed tensor size: {squeezed_y.shape}")
# lets perform unsqueezing
y_unsquezzed = squeezed_y.unsqueeze(dim = 0) # try different dimensions
print(f"Present unsqueezed tensor: {y_unsquezzed}")
print(f"Present unsqueezed tensor shape: {y_unsquezzed.shape}")

Previous squeezed tensor: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Previous squeezed tensor size: torch.Size([10])
Present unsqueezed tensor: tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])
Present unsqueezed tensor shape: torch.Size([1, 10])
